name: Cleanup History

on: [push]

permissions:
  contents: read
  deployments: write
  id-token: write

env:
  GO_VERSION: '^1.13.1'

jobs:
  build:
    name: Build Site
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: $GO_VERSION

      - name: Build Binary
        run: go build atCleanup.go

      - name: Cleanup UY
        run: ./atCleanup --did=$DID --password=$PASS --types=post,repost,like --days=20 --rate-limit=4 --burst-limit=1
        env:
          DID: ${{ vars.UY_DID }}
          PASS: ${{ vars.UY_PASS }}


      - name: Cleanup FOE
        run: ./atCleanup --did=$DID --password=$PASS --types=post,repost,like --days=20 --rate-limit=4 --burst-limit=1
        env:
          DID: ${{ vars.FOE_DID }}
          PASS: ${{ vars.FOE_PASS }}
